quattor/CAF

- src/main/perl/FileEditor.pm
- src/main/perl/FileReader.pm
partially fixes https://github.com/quattor/CCM/issues/46
> FileReader can read from a pipe

- pom.xml
> Remove stray quote in pom

- src/main/perl/TextRender.pm
- src/test/perl/textrender.t
- src/test/resources/rendertest/path1/main.tt
- src/test/resources/rendertest/path2/othermain.tt
Fixes #81
`general` / Config::General has reproducability issues, should be avoided if possible
> TextRender: general/Config::General disable SaveSorted and enable ForceArray

- src/main/perl/Reporter.pm
- src/main/perl/TextRender.pm
- src/test/perl/textrender.t
Fixes https://github.com/quattor/ncm-lib-blockdevices/issues/59
> Localize $@ when using eval

- src/test/perl/test-caffileeditor_add_or_replace.t
> CAF test: make copy of constant before set_contents

- src/main/perl/Application.pm
- src/main/perl/Object.pm
- src/main/perl/ObjectText.pm
- src/main/perl/TextRender.pm
- src/test/perl/modules/myobjecttext.pm
- src/test/perl/object.t
- src/test/perl/objecttext.t
- src/test/perl/test-cafapplication.t
- src/test/perl/textrender.t
> Application: Support non-option arguments retrieval via arrayref 

- src/main/perl/Application.pm
- src/main/perl/Log.pm
- src/test/perl/log.t
- src/test/perl/modules/testapp.pm
- src/test/perl/test-cafapplication.t
Fixes #93
Based on #126
Adding support to ncm-ncd is handled in https://github.com/quattor/ncm-ncd/issues/55
> Support PID logging

- src/main/perl/Kerberos.pm
- src/main/perl/Object.pm
- src/test/perl/kerberos-process.t
- src/test/perl/kerberos.t
- src/test/perl/object.t
Based on #120 
Important to note that kinit is not required at all.
> Kerberos support via GSSAPI

- src/main/perl/Application.pm
- src/main/perl/Lock.pm
- src/main/perl/Log.pm
> CAF: cleanup remove prototypes

- src/main/perl/Reporter.pm
- src/main/perl/ReporterMany.pm
- src/test/perl/reporter.t
> Reporter: add methods to query state of reporter

- pom.xml
Requires https://github.com/quattor/maven-tools/pull/78
> pom: Fix rpmlint errors

- src/main/perl/FileEditor.pm
- src/main/perl/FileWriter.pm
- src/main/perl/RuleBasedEditor.pm
- src/test/perl/test-caffilewriter.t
Requires new build-scripts with https://github.com/quattor/maven-tools/pull/80
> FileWriter: add conditional logger interfaces

- src/main/perl/FileEditor.pm
> FileEditor: fix unitialized warning in debug message 

- .gitignore
Add PyCharm project files (.idea/) and Eclipse project file to .gitignore
> Add PyCharm and Eclipse files to gitignore

- src/main/perl/Lock.pm
- src/test/perl/lock.t
> Lock: handle existing old-style locks

- src/main/perl/Reporter.pm
- src/test/perl/reporter.t
> Reporter: handle non-printable characters

- src/main/perl/Path.pm
- src/test/perl/path.t
Add support for `move`ing (/renaming) files and directories
> Path: support move method

- src/main/perl/FileWriter.pm
- src/test/perl/test-caffilewriter.t
> FileWriter: support for setting file modification time via mtime option

- src/main/perl/Process.pm
- src/test/perl/test-cafprocess.t
> Process: factor out LC::Process calls for consistent behaviour

- src/main/perl/Reporter.pm
- src/test/perl/reporter.t
> Reporter: support VERBOSE_LOGFILE to always log verbose to logfile

- src/main/perl/Kerberos.pm
- src/test/perl/kerberos.t
This is not required on EL7, but seems like a new feature in EL7 rather than a bug on EL6
> Kerberos: get a TGT using kinit as part of create_credential_cache

- src/main/perl/Path.pm
- src/test/perl/path.t
> Path: untaint paths

- src/main/perl/FileWriter.pm
- src/test/perl/test-caffilewriter.t
Requires https://github.com/quattor/ncm-ncd/pull/96
Fixes #153
> Remove add_files to track files

- src/main/perl/RuleBasedEditor.pm
> RuleBasedEditor: use CCM::Path for unescape

- pom.xml
- src/main/perl/Application.pm
- src/main/perl/FileEditor.pm
- src/main/perl/FileReader.pm
- src/main/perl/FileWriter.pm
- src/main/perl/History.pm
- src/main/perl/Kerberos.pm
- src/main/perl/Lock.pm
- src/main/perl/Log.pm
- src/main/perl/Object.pm
- src/main/perl/ObjectText.pm
- src/main/perl/Path.pm
- src/main/perl/RuleBasedEditor.pm
- src/main/perl/Service.pm
- src/main/perl/TextRender.pm
- src/test/perl/00-tqu.t
- src/test/perl/release-pod-syntax.t
- src/test/perl/test-caffileeditor_add_or_replace.t
- src/test/perl/test-caffileeditor_source.t
Requires release of new build tools
> Switch to 00-tqu

- src/main/perl/FileWriter.pm
> FileWriter: resolve cyclic dependency

- src/test/perl/reporter.t
> Reporter: support struct logging and templating using old TT without STRICT support (eg el5)

- src/main/perl/Path.pm
Just to make problem troubleshooting easier...
> Path.pm: add a debug message in _make_link

- src/main/perl/Path.pm
- src/test/perl/path.t
Fixes https://github.com/quattor/configuration-modules-core/issues/991
> Path: move: do not cleanup dest, but add backup of dest using hardlink

- src/main/perl/FileWriter.pm
- src/test/perl/filewriter.t
> Filewriter: support sensitive option

- pom.xml
- src/main/perl/RuleBasedEditor.pm
> Update build tools to 1.53

- src/main/perl/FileEditor.pm
- src/main/perl/FileReader.pm
- src/main/perl/FileWriter.pm
- src/main/perl/Reporter.pm
- src/test/perl/fileeditor_source.t
- src/test/perl/reporter.t
Fixes #237 
Also fixes #236 and fixes #239
> FileWriter/Editor: fix bug in close with source

- src/main/perl/FileWriter.pm
- src/test/perl/filewriter.t
> FileWriter: better handle already closed file

- src/main/perl/FileWriter.pm
- src/test/perl/fileeditor.t
- src/test/perl/fileeditor_source.t
- src/test/perl/filewriter-notmocked.t
- src/test/perl/filewriter.t
- src/test/perl/rulebasededitor.t
> FileWriter: set file status when no content was modified

- src/main/perl/TextRender.pm
- src/test/perl/textrender.t
add module to Indent json and add spaces before and after
> TextRender: add jsonpretty module

- pom.xml
> Make project name consistent with other repos and add RPM description

- src/main/perl/ReporterMany.pm
- src/main/perl/TextRender.pm
- src/test/perl/exception.t
AFAICT this preserves existing behaviour.
Resolves #109.
> Replace four instances of while-each with foreach
